codecov:
  notify:
    require_ci_to_pass: yes
comment: on
coverage:
  precision: 2
  round: up
  range: "80...100"
  status:
    patch:
      default:
        threshold: "5%"
        only_pulls: true
    project:
      pytest_terraform:
        paths: "pytest_terraform"
        threshold: "0.1%"
      default: off
